# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # app
  config.vm.define "app" do |app|
	app.vm.hostname = "app.test"
	app.vm.network :private_network, ip: "192.168.50.5"
  end
end
